# Generated by Django 3.1.2 on 2020-10-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('functionID', models.AutoField(primary_key=True, serialize=False)),
                ('functionName', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(default='', max_length=200)),
                ('roleFunction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testDeployApp.function')),
            ],
        ),
    ]
