# Generated by Django 3.1.2 on 2020-10-23 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testDeployApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expertId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=50)),
                ('expertiseFunction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testDeployApp.function')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=50)),
                ('interestedRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testDeployApp.role')),
            ],
        ),
    ]
